import { TarotCard } from "./types";

// Base URL for card images
// Using local images stored in public folder for better performance and offline support
const LOCAL_CDN = `${import.meta.env.BASE_URL}images/cards/`;
// Fallback to Sacred Texts Archive if local images are not available
const REMOTE_CDN = "https://www.sacred-texts.com/tarot/pkt/img/";

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: 0,
    nameEn: "The Fool",
    nameCn: "愚人",
    keywords: ["无限潜力", "新的开始", "纯真", "自由", "冒险"],
    image: "ar00.jpg",
  },
  {
    id: 1,
    nameEn: "The Magician",
    nameCn: "魔术师",
    keywords: ["显化", "意志力", "创造", "资源", "专注"],
    image: "ar01.jpg",
  },
  {
    id: 2,
    nameEn: "The High Priestess",
    nameCn: "女祭司",
    keywords: ["直觉", "潜意识", "神秘", "内在智慧", "静默"],
    image: "ar02.jpg",
  },
  {
    id: 3,
    nameEn: "The Empress",
    nameCn: "皇后",
    keywords: ["丰饶", "自然", "母性", "感官享受", "孕育"],
    image: "ar03.jpg",
  },
  {
    id: 4,
    nameEn: "The Emperor",
    nameCn: "皇帝",
    keywords: ["权威", "结构", "控制", "父亲原型", "秩序"],
    image: "ar04.jpg",
  },
  {
    id: 5,
    nameEn: "The Hierophant",
    nameCn: "教皇",
    keywords: ["传统", "信仰", "教导", "社会规范", "精神指引"],
    image: "ar05.jpg",
  },
  {
    id: 6,
    nameEn: "The Lovers",
    nameCn: "恋人",
    keywords: ["爱", "和谐", "价值观", "选择", "结合"],
    image: "ar06.jpg",
  },
  {
    id: 7,
    nameEn: "The Chariot",
    nameCn: "战车",
    keywords: ["意志力", "胜利", "决心", "自我掌控", "进取"],
    image: "ar07.jpg",
  },
  {
    id: 8,
    nameEn: "Strength",
    nameCn: "力量",
    keywords: ["勇气", "耐心", "同情", "内在力量", "驯服"],
    image: "ar08.jpg",
  },
  {
    id: 9,
    nameEn: "The Hermit",
    nameCn: "隐士",
    keywords: ["内省", "孤独", "寻求真理", "指引", "撤退"],
    image: "ar09.jpg",
  },
  {
    id: 10,
    nameEn: "Wheel of Fortune",
    nameCn: "命运之轮",
    keywords: ["宿命", "转折点", "周期", "运气", "改变"],
    image: "ar10.jpg",
  },
  {
    id: 11,
    nameEn: "Justice",
    nameCn: "正义",
    keywords: ["公平", "真理", "因果", "法律", "平衡"],
    image: "ar11.jpg",
  },
  {
    id: 12,
    nameEn: "The Hanged Man",
    nameCn: "倒吊人",
    keywords: ["牺牲", "等待", "新视角", "放下", "暂停"],
    image: "ar12.jpg",
  },
  {
    id: 13,
    nameEn: "Death",
    nameCn: "死神",
    keywords: ["结束", "重生", "转变", "必然性", "过渡"],
    image: "ar13.jpg",
  },
  {
    id: 14,
    nameEn: "Temperance",
    nameCn: "节制",
    keywords: ["平衡", "温和", "调和", "耐心", "炼金术"],
    image: "ar14.jpg",
  },
  {
    id: 15,
    nameEn: "The Devil",
    nameCn: "恶魔",
    keywords: ["束缚", "物质主义", "诱惑", "阴影", "成瘾"],
    image: "ar15.jpg",
  },
  {
    id: 16,
    nameEn: "The Tower",
    nameCn: "高塔",
    keywords: ["剧变", "启示", "破坏", "觉醒", "混乱"],
    image: "ar16.jpg",
  },
  {
    id: 17,
    nameEn: "The Star",
    nameCn: "星星",
    keywords: ["希望", "灵感", "宁静", "疗愈", "更新"],
    image: "ar17.jpg",
  },
  {
    id: 18,
    nameEn: "The Moon",
    nameCn: "月亮",
    keywords: ["幻觉", "潜意识", "不安", "梦境", "直觉"],
    image: "ar18.jpg",
  },
  {
    id: 19,
    nameEn: "The Sun",
    nameCn: "太阳",
    keywords: ["快乐", "成功", "活力", "清晰", "温暖"],
    image: "ar19.jpg",
  },
  {
    id: 20,
    nameEn: "Judgement",
    nameCn: "审判",
    keywords: ["觉醒", "反思", "重生", "召唤", "赦免"],
    image: "ar20.jpg",
  },
  {
    id: 21,
    nameEn: "The World",
    nameCn: "世界",
    keywords: ["圆满", "完成", "旅行", "成就", "整体"],
    image: "ar21.jpg",
  },
];

// Specific definitions for the 56 Minor Arcana cards
export const MINOR_ARCANA: TarotCard[] = [
  // --- WANDS (Fire / Action) ---
  {
    id: 22,
    nameEn: "Ace of Wands",
    nameCn: "权杖首牌",
    keywords: ["灵感", "新机会", "创造力", "潜力"],
    image: "waac.jpg",
  },
  {
    id: 23,
    nameEn: "Two of Wands",
    nameCn: "权杖二",
    keywords: ["未来规划", "决定", "发现", "掌控"],
    image: "wa02.jpg",
  },
  {
    id: 24,
    nameEn: "Three of Wands",
    nameCn: "权杖三",
    keywords: ["扩张", "远见", "海外", "进步"],
    image: "wa03.jpg",
  },
  {
    id: 25,
    nameEn: "Four of Wands",
    nameCn: "权杖四",
    keywords: ["庆祝", "和谐", "回家", "安稳"],
    image: "wa04.jpg",
  },
  {
    id: 26,
    nameEn: "Five of Wands",
    nameCn: "权杖五",
    keywords: ["冲突", "竞争", "分歧", "挑战"],
    image: "wa05.jpg",
  },
  {
    id: 27,
    nameEn: "Six of Wands",
    nameCn: "权杖六",
    keywords: ["胜利", "认可", "自信", "成就"],
    image: "wa06.jpg",
  },
  {
    id: 28,
    nameEn: "Seven of Wands",
    nameCn: "权杖七",
    keywords: ["防御", "坚持", "挑战", "勇气"],
    image: "wa07.jpg",
  },
  {
    id: 29,
    nameEn: "Eight of Wands",
    nameCn: "权杖八",
    keywords: ["速度", "行动", "消息", "快速变化"],
    image: "wa08.jpg",
  },
  {
    id: 30,
    nameEn: "Nine of Wands",
    nameCn: "权杖九",
    keywords: ["韧性", "防御", "最后坚持", "疲惫"],
    image: "wa09.jpg",
  },
  {
    id: 31,
    nameEn: "Ten of Wands",
    nameCn: "权杖十",
    keywords: ["负担", "责任", "压力", "努力"],
    image: "wa10.jpg",
  },
  {
    id: 32,
    nameEn: "Page of Wands",
    nameCn: "权杖侍从",
    keywords: ["探索", "新想法", "热情", "自由"],
    image: "wapa.jpg",
  },
  {
    id: 33,
    nameEn: "Knight of Wands",
    nameCn: "权杖骑士",
    keywords: ["冲动", "激情", "行动", "冒险"],
    image: "wakn.jpg",
  },
  {
    id: 34,
    nameEn: "Queen of Wands",
    nameCn: "权杖王后",
    keywords: ["自信", "独立", "社交", "活力"],
    image: "waqu.jpg",
  },
  {
    id: 35,
    nameEn: "King of Wands",
    nameCn: "权杖国王",
    keywords: ["领导", "远见", "企业家", "荣誉"],
    image: "waki.jpg",
  },

  // --- CUPS (Water / Emotion) ---
  {
    id: 36,
    nameEn: "Ace of Cups",
    nameCn: "圣杯首牌",
    keywords: ["新感情", "同情", "创造力", "灵性"],
    image: "cuac.jpg",
  },
  {
    id: 37,
    nameEn: "Two of Cups",
    nameCn: "圣杯二",
    keywords: ["伴侣", "结合", "吸引", "平等"],
    image: "cu02.jpg",
  },
  {
    id: 38,
    nameEn: "Three of Cups",
    nameCn: "圣杯三",
    keywords: ["友谊", "社群", "聚会", "快乐"],
    image: "cu03.jpg",
  },
  {
    id: 39,
    nameEn: "Four of Cups",
    nameCn: "圣杯四",
    keywords: ["冷漠", "沉思", "错失机会", "厌倦"],
    image: "cu04.jpg",
  },
  {
    id: 40,
    nameEn: "Five of Cups",
    nameCn: "圣杯五",
    keywords: ["悲伤", "失望", "遗憾", "丧失"],
    image: "cu05.jpg",
  },
  {
    id: 41,
    nameEn: "Six of Cups",
    nameCn: "圣杯六",
    keywords: ["怀旧", "童年", "纯真", "重逢"],
    image: "cu06.jpg",
  },
  {
    id: 42,
    nameEn: "Seven of Cups",
    nameCn: "圣杯七",
    keywords: ["幻觉", "选择", "白日梦", "困惑"],
    image: "cu07.jpg",
  },
  {
    id: 43,
    nameEn: "Eight of Cups",
    nameCn: "圣杯八",
    keywords: ["离开", "寻找", "放弃", "旅行"],
    image: "cu08.jpg",
  },
  {
    id: 44,
    nameEn: "Nine of Cups",
    nameCn: "圣杯九",
    keywords: ["满足", "愿望成真", "感激", "享受"],
    image: "cu09.jpg",
  },
  {
    id: 45,
    nameEn: "Ten of Cups",
    nameCn: "圣杯十",
    keywords: ["和谐", "幸福", "家庭", "团圆"],
    image: "cu10.jpg",
  },
  {
    id: 46,
    nameEn: "Page of Cups",
    nameCn: "圣杯侍从",
    keywords: ["直觉", "创意", "新消息", "敏感"],
    image: "cupa.jpg",
  },
  {
    id: 47,
    nameEn: "Knight of Cups",
    nameCn: "圣杯骑士",
    keywords: ["浪漫", "魅力", "想象力", "追求"],
    image: "cukn.jpg",
  },
  {
    id: 48,
    nameEn: "Queen of Cups",
    nameCn: "圣杯王后",
    keywords: ["慈悲", "关怀", "情感", "直觉"],
    image: "cuqu.jpg",
  },
  {
    id: 49,
    nameEn: "King of Cups",
    nameCn: "圣杯国王",
    keywords: ["情绪平衡", "控制", "宽容", "外交"],
    image: "cuki.jpg",
  },

  // --- SWORDS (Air / Intellect) ---
  {
    id: 50,
    nameEn: "Ace of Swords",
    nameCn: "宝剑首牌",
    keywords: ["突破", "清晰", "真理", "决断"],
    image: "swac.jpg",
  },
  {
    id: 51,
    nameEn: "Two of Swords",
    nameCn: "宝剑二",
    keywords: ["僵局", "艰难决定", "回避", "权衡"],
    image: "sw02.jpg",
  },
  {
    id: 52,
    nameEn: "Three of Swords",
    nameCn: "宝剑三",
    keywords: ["心碎", "悲伤", "痛苦", "分离"],
    image: "sw03.jpg",
  },
  {
    id: 53,
    nameEn: "Four of Swords",
    nameCn: "宝剑四",
    keywords: ["休息", "恢复", "沉思", "被动"],
    image: "sw04.jpg",
  },
  {
    id: 54,
    nameEn: "Five of Swords",
    nameCn: "宝剑五",
    keywords: ["失败", "背叛", "冲突", "空虚的胜利"],
    image: "sw05.jpg",
  },
  {
    id: 55,
    nameEn: "Six of Swords",
    nameCn: "宝剑六",
    keywords: ["过渡", "离开", "治愈", "前进"],
    image: "sw06.jpg",
  },
  {
    id: 56,
    nameEn: "Seven of Swords",
    nameCn: "宝剑七",
    keywords: ["欺骗", "策略", "隐秘", "逃避"],
    image: "sw07.jpg",
  },
  {
    id: 57,
    nameEn: "Eight of Swords",
    nameCn: "宝剑八",
    keywords: ["束缚", "受害者心态", "无助", "限制"],
    image: "sw08.jpg",
  },
  {
    id: 58,
    nameEn: "Nine of Swords",
    nameCn: "宝剑九",
    keywords: ["焦虑", "噩梦", "担忧", "恐惧"],
    image: "sw09.jpg",
  },
  {
    id: 59,
    nameEn: "Ten of Swords",
    nameCn: "宝剑十",
    keywords: ["毁灭", "痛苦结局", "背叛", "最低点"],
    image: "sw10.jpg",
  },
  {
    id: 60,
    nameEn: "Page of Swords",
    nameCn: "宝剑侍从",
    keywords: ["好奇", "警惕", "新想法", "沟通"],
    image: "swpa.jpg",
  },
  {
    id: 61,
    nameEn: "Knight of Swords",
    nameCn: "宝剑骑士",
    keywords: ["急躁", "直接", "行动", "野心"],
    image: "swkn.jpg",
  },
  {
    id: 62,
    nameEn: "Queen of Swords",
    nameCn: "宝剑王后",
    keywords: ["敏锐", "独立", "清晰", "界限"],
    image: "swqu.jpg",
  },
  {
    id: 63,
    nameEn: "King of Swords",
    nameCn: "宝剑国王",
    keywords: ["理智", "权威", "真理", "公正"],
    image: "swki.jpg",
  },

  // --- PENTACLES (Earth / Material) ---
  {
    id: 64,
    nameEn: "Ace of Pentacles",
    nameCn: "星币首牌",
    keywords: ["新机会", "繁荣", "丰富", "表现"],
    image: "peac.jpg",
  },
  {
    id: 65,
    nameEn: "Two of Pentacles",
    nameCn: "星币二",
    keywords: ["平衡", "适应", "优先顺位", "灵活"],
    image: "pe02.jpg",
  },
  {
    id: 66,
    nameEn: "Three of Pentacles",
    nameCn: "星币三",
    keywords: ["团队", "合作", "技能", "计划"],
    image: "pe03.jpg",
  },
  {
    id: 67,
    nameEn: "Four of Pentacles",
    nameCn: "星币四",
    keywords: ["控制", "占有", "保守", "安全"],
    image: "pe04.jpg",
  },
  {
    id: 68,
    nameEn: "Five of Pentacles",
    nameCn: "星币五",
    keywords: ["贫穷", "孤立", "不安全", "困难"],
    image: "pe05.jpg",
  },
  {
    id: 69,
    nameEn: "Six of Pentacles",
    nameCn: "星币六",
    keywords: ["慈善", "慷慨", "分享", "平衡"],
    image: "pe06.jpg",
  },
  {
    id: 70,
    nameEn: "Seven of Pentacles",
    nameCn: "星币七",
    keywords: ["耐心", "投资", "等待", "长期规划"],
    image: "pe07.jpg",
  },
  {
    id: 71,
    nameEn: "Eight of Pentacles",
    nameCn: "星币八",
    keywords: ["勤奋", "技能", "工艺", "细节"],
    image: "pe08.jpg",
  },
  {
    id: 72,
    nameEn: "Nine of Pentacles",
    nameCn: "星币九",
    keywords: ["富足", "奢华", "自给自足", "成就"],
    image: "pe09.jpg",
  },
  {
    id: 73,
    nameEn: "Ten of Pentacles",
    nameCn: "星币十",
    keywords: ["财富", "遗产", "家庭", "长期成功"],
    image: "pe10.jpg",
  },
  {
    id: 74,
    nameEn: "Page of Pentacles",
    nameCn: "星币侍从",
    keywords: ["好学", "务实", "新机会", "显化"],
    image: "pepa.jpg",
  },
  {
    id: 75,
    nameEn: "Knight of Pentacles",
    nameCn: "星币骑士",
    keywords: ["勤奋", "效率", "例行公事", "保守"],
    image: "pekn.jpg",
  },
  {
    id: 76,
    nameEn: "Queen of Pentacles",
    nameCn: "星币王后",
    keywords: ["养育", "务实", "安全", "居家"],
    image: "pequ.jpg",
  },
  {
    id: 77,
    nameEn: "King of Pentacles",
    nameCn: "星币国王",
    keywords: ["富裕", "商业", "领导", "安全感"],
    image: "peki.jpg",
  },
];

// Helper to get image URL with fallback support
// Tries local image first, falls back to remote CDN if not available
export const getCardImageUrl = (image: string) => `${LOCAL_CDN}${image}`;
export const getCardImageFallbackUrl = (image: string) =>
  `${REMOTE_CDN}${image}`;

export const FULL_DECK: TarotCard[] = [...MAJOR_ARCANA, ...MINOR_ARCANA];

// Pre-defined scripts for the static voice parts
export const STATIC_SCRIPTS = {
  WELCOME: "静心凝视深渊。当你的直觉苏醒时，进入命运之门。",
  ASK: "心中的疑惑，是通往真理的钥匙。告诉我，你为何而来？",
  SHUFFLE: "星辰正在归位，混乱中孕育着秩序。专注于你的问题。",
  PICK: "在流动的命运中，选择你的指引。",
  REVEAL: "这就是……命运的回响。",
};
